# Data understanding

In [203]:
import pandas as pd 
import numpy as np
df = pd.read_csv('Data/Aviation_Data.csv')
df

/Users/DonJuve/anaconda3/envs/learn-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (6,7,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90343,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
90344,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90345,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
90346,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90347,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90348 entries, 0 to 90347
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      90348 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50249 non-null  object
 9   Airport.Name            52790 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87572 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81812 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82508 non-null  object
 30  Publication.Date        73659 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.4+ MB

In [205]:
df['Total.Fatal.Injuries']

0        2.0
1        4.0
2        3.0
3        2.0
4        1.0
        ...
90343    0.0
90344    0.0
90345    0.0
90346    0.0
90347    0.0
Name: Total.Fatal.Injuries, Length: 90348, dtype: float64

In [206]:
df['Total.Fatal.Injuries'].isna().sum()

12860

In [207]:
df['Total.Fatal.Injuries'].isna().sum()

12860

In [208]:
df['Total.Fatal.Injuries'].isna().sum()

12860

In [209]:
df['Total.Serious.Injuries'].isna().sum()

13969

In [210]:
df['Total.Minor.Injuries'].isna().sum()

13392

In [211]:
df['Total.Uninjured'].isna().sum()

7371

In [212]:
df['Report.Status'].isna().sum()

7840

In [213]:
df['Event.Date'].isna().sum()

1459

# Data Preparation

We will start by removing all the null value of the following colums of our Data Frames: 'Engine.Type','Model','Event.Date','Make','Injury.Severity','Total.Fatal.Injuries','Total.Serious.Injuries','Total.Minor.Injuries','Total.Uninjured'

In [214]:
df = df.dropna(subset=['Engine.Type','Model','Event.Date','Make','Injury.Severity','Total.Fatal.Injuries','Total.Serious.Injuries','Total.Minor.Injuries','Total.Uninjured' ])

In [215]:
df.shape

(68490, 31)

In [216]:
#verfication
df['Total.Serious.Injuries'].isna().sum()

0

In [217]:
df['Total.Uninjured'].isna().sum()

0

Verification of duplicate Values

In [218]:
df.duplicated().value_counts()
#to remove duplicates data

False    68490
dtype: int64

In [219]:
#remove all duplicates values
df = df.drop_duplicates()

In [220]:
#Sanity check
df.duplicated().value_counts()

False    68490
dtype: int64

In [221]:
df.shape

(68490, 31)

Normalization

In [222]:
df['Make']

0                  Stinson
1                    Piper
3                 Rockwell
6                   Cessna
7                   Cessna
               ...
90098               CESSNA
90106               CESSNA
90120                BEECH
90194    STEPHEN J HOFFMAN
90226             LUSCOMBE
Name: Make, Length: 68490, dtype: object

In [223]:
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
6,20001218X45446,Accident,CHI81LA106,1981-08-01,"COTTON, MN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,IMC,Unknown,Probable Cause,06-11-2001
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90098,20221011106092,Accident,CEN23LA008,2022-10-06,"Iola, TX",United States,304354N,0096752W,PVT,Private,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots failure to maintain control of the...,20-12-2022
90106,20221011106098,Accident,ERA23LA014,2022-10-08,"Dacula, GA",United States,034055N,0835224W,LZU,GWINNETT COUNTY - BRISCOE FLD,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,An in-flight collision with a bird while on ap...,20-12-2022
90120,20221018106153,Accident,CEN23LA015,2022-10-13,"Ardmore, OK",United States,034849N,0097722W,1F0,Ardmore Downtown Executive Air,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilot did not ensure adequate clearance fr...,20-12-2022
90194,20221031106231,Accident,CEN23LA023,2022-10-29,"Houston, TX",United States,293620N,0095959W,EFD,ELLINGTON,...,ASHO,NaN,0.0,1.0,0.0,0.0,VMC,NaN,The pilots failure to secure the magneto swit...,20-12-2022
90226,20221109106272,Accident,CEN23LA033,2022-11-09,"Bridgeport, TX",United States,331026N,0974943W,KXBP,Bridgeport Municipal,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The pilots loss of control due to a wind gust...,20-12-2022

In [224]:
df['Make']

0                  Stinson
1                    Piper
3                 Rockwell
6                   Cessna
7                   Cessna
               ...
90098               CESSNA
90106               CESSNA
90120                BEECH
90194    STEPHEN J HOFFMAN
90226             LUSCOMBE
Name: Make, Length: 68490, dtype: object

In [225]:
df['Make'] = df['Make'].str.capitalize()

In [226]:
df['Aircraft.Category'].unique()

array([nan, 'Airplane', 'Helicopter', 'Glider', 'Balloon', 'Gyrocraft',
       'Ultralight', 'Unknown', 'Weight-Shift', 'Powered Parachute',
       'Rocket', 'Blimp', 'WSFT'], dtype=object)

In [227]:
#df = df[df['Aircraft.Category'].str.lower().str.contains('airplane', na=False)]zz

In [228]:
df = df[df['Aircraft.Category'] == 'Airplane']
df['Aircraft.Category']

7        Airplane
8        Airplane
12       Airplane
13       Airplane
14       Airplane
           ...
90098    Airplane
90106    Airplane
90120    Airplane
90194    Airplane
90226    Airplane
Name: Aircraft.Category, Length: 19883, dtype: object

In [229]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19883 entries, 7 to 90226
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                19883 non-null  object
 1   Investigation.Type      19883 non-null  object
 2   Accident.Number         19883 non-null  object
 3   Event.Date              19883 non-null  object
 4   Location                19883 non-null  object
 5   Country                 19877 non-null  object
 6   Latitude                16449 non-null  object
 7   Longitude               16449 non-null  object
 8   Airport.Code            13762 non-null  object
 9   Airport.Name            14398 non-null  object
 10  Injury.Severity         19883 non-null  object
 11  Aircraft.damage         19456 non-null  object
 12  Aircraft.Category       19883 non-null  object
 13  Registration.Number     19881 non-null  object
 14  Make                    19883 non-null  object
 15  Model                   19883 non-null  object
 16  Amateur.Built           19883 non-null  object
 17  Number.of.Engines       19388 non-null  float64
 18  Engine.Type             19883 non-null  object
 19  FAR.Description         19782 non-null  object
 20  Schedule                1626 non-null   object
 21  Purpose.of.flight       18615 non-null  object
 22  Air.carrier             9157 non-null   object
 23  Total.Fatal.Injuries    19883 non-null  float64
 24  Total.Serious.Injuries  19883 non-null  float64
 25  Total.Minor.Injuries    19883 non-null  float64
 26  Total.Uninjured         19883 non-null  float64
 27  Weather.Condition       19338 non-null  object
 28  Broad.phase.of.flight   3228 non-null   object
 29  Report.Status           18771 non-null  object
 30  Publication.Date        18650 non-null  object
dtypes: float64(5), object(26)
memory usage: 4.9+ MB

In [231]:
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
14,20020917X02119,Accident,FTW82FPJ10,1982-01-02,"CHICKASHA, OK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90098,20221011106092,Accident,CEN23LA008,2022-10-06,"Iola, TX",United States,304354N,0096752W,PVT,Private,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots failure to maintain control of the...,20-12-2022
90106,20221011106098,Accident,ERA23LA014,2022-10-08,"Dacula, GA",United States,034055N,0835224W,LZU,GWINNETT COUNTY - BRISCOE FLD,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,An in-flight collision with a bird while on ap...,20-12-2022
90120,20221018106153,Accident,CEN23LA015,2022-10-13,"Ardmore, OK",United States,034849N,0097722W,1F0,Ardmore Downtown Executive Air,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilot did not ensure adequate clearance fr...,20-12-2022
90194,20221031106231,Accident,CEN23LA023,2022-10-29,"Houston, TX",United States,293620N,0095959W,EFD,ELLINGTON,...,ASHO,NaN,0.0,1.0,0.0,0.0,VMC,NaN,The pilots failure to secure the magneto swit...,20-12-2022
90226,20221109106272,Accident,CEN23LA033,2022-11-09,"Bridgeport, TX",United States,331026N,0974943W,KXBP,Bridgeport Municipal,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The pilots loss of control due to a wind gust...,20-12-2022

In [237]:
df['Make'].value_counts()

Cessna               6261
Piper                3619
Beech                1267
Boeing                377
Mooney                310
                     ...
Abbey victor            1
Combs dale b            1
Eichhorn gary l         1
Hauser u/hauser j       1
Navy                    1
Name: Make, Length: 2868, dtype: int64

In [246]:
df_20 = df[df['Make'].isin(df['Make'].value_counts().nlargest(20).index)]

In [247]:
#df = df[df['Aircraft.Category'] == 'Airplane']
df_personal = df_20[df_20['Purpose.of.flight'] == 'Personal']

In [248]:
df_personal

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
15,20020917X02117,Accident,FTW82FPG08,1982-01-02,"LITTLE ROCK, AR",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
17,20020917X01656,Accident,ANC82FAG14,1982-01-02,"SKWENTA, AK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,3.0,0.0,0.0,0.0,VMC,Unknown,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90089,20221011106095,Accident,CEN23LA011,2022-10-05,"Navasota, TX",United States,302315N,0096516W,60R,Navasota,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots loss of control while landing resu...,NaN
90098,20221011106092,Accident,CEN23LA008,2022-10-06,"Iola, TX",United States,304354N,0096752W,PVT,Private,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots failure to maintain control of the...,20-12-2022
90106,20221011106098,Accident,ERA23LA014,2022-10-08,"Dacula, GA",United States,034055N,0835224W,LZU,GWINNETT COUNTY - BRISCOE FLD,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,An in-flight collision with a bird while on ap...,20-12-2022
90120,20221018106153,Accident,CEN23LA015,2022-10-13,"Ardmore, OK",United States,034849N,0097722W,1F0,Ardmore Downtown Executive Air,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilot did not ensure adequate clearance fr...,20-12-2022
90226,20221109106272,Accident,CEN23LA033,2022-11-09,"Bridgeport, TX",United States,331026N,0974943W,KXBP,Bridgeport Municipal,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The pilots loss of control due to a wind gust...,20-12-2022

In [249]:
df_business = df_20[df_20['Purpose.of.flight'] == 'Business']

In [259]:
#filtered_df = df[(df['Total.Fatal.Injuries'] == 0) & (df['Total.Serious.Injuries'] == 0) & (df['Total.Minor.Injuries'] == 0)]

In [264]:
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

Safety Metric Calculation :

In [272]:
# first lets determine the total of the overall Injuries
df['Total.Injuries'] = df[['Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries']].sum(axis=1)

<ipython-input-272-22fa7f96697f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Total.Injuries'] = df[['Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries']].sum(axis=1)

In [293]:
df['Fatality.Rate'] = df['Total.Fatal.Injuries'] / df['Total.Injuries']

<ipython-input-293-6203992b400f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Fatality.Rate'] = df['Total.Fatal.Injuries'] / df['Total.Injuries']

In [291]:
#  Calculate Safety Metrics
#df['Total.Injuries'] = df[safety_columns[:-1]].sum(axis=1)
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Total.Injuries,Fatality.Rate
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982,0.0,NaN
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982,0.0,NaN
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983,1.0,0.0
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983,1.0,1.0
14,20020917X02119,Accident,FTW82FPJ10,1982-01-02,"CHICKASHA, OK",United States,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983,1.0,1.0

Group data by categorie using the colummn Make

In [294]:
df_new = df.groupby('Make')

In [295]:
df_new.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Total.Injuries,Fatality.Rate
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982,0.0,NaN
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982,0.0,NaN
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983,1.0,0.0
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983,1.0,1.0
14,20020917X02119,Accident,FTW82FPJ10,1982-01-02,"CHICKASHA, OK",United States,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89995,20220919105966,Accident,CEN22LA425,2022-09-17,"Delphi, IN",United States,403225N,0864052W,1I9,DELPHI MUNI,...,0.0,0.0,0.0,2.0,VMC,NaN,A loss of engine power due to carburetor icing.,15-12-2022,0.0,NaN
90009,20220920105975,Accident,CEN22LA426,2022-09-20,"Lebanon, IN",United States,040026N,0862626W,6I4,BOONE COUNTY,...,0.0,0.0,0.0,1.0,VMC,NaN,The loss of lateral/bank control during takeof...,NaN,0.0,NaN
90030,20220927106002,Accident,CEN22LA432,2022-09-25,"Del Norte, CO",United States,374250N,0106217W,RCV,Astronaut Kent Rominger,...,0.0,1.0,0.0,0.0,VMC,NaN,The pilots loss of airplane control during la...,NaN,1.0,0.0
90096,20221011106091,Accident,CEN23LA007,2022-10-06,"Waldron, AR",United States,345233N,0094638W,M27,M27,...,0.0,0.0,0.0,1.0,VMC,NaN,The pilots failure to maintain adequate airsp...,NaN,0.0,NaN
90194,20221031106231,Accident,CEN23LA023,2022-10-29,"Houston, TX",United States,293620N,0095959W,EFD,ELLINGTON,...,0.0,1.0,0.0,0.0,VMC,NaN,The pilots failure to secure the magneto swit...,20-12-2022,1.0,0.0

In [300]:
ranked_companies = df_new[['Total.Fatal.Injuries', 'Total.Injuries', 'Fatality.Rate']].sum()
ranked_companies['Incident.Count'] = df_new.size()
ranked_companies['Rank'] = ranked_companies['Total.Fatal.Injuries'].rank(ascending=True)

In [301]:
print(ranked_companies.sort_values(by='Rank'))

                  Total.Fatal.Injuries  Total.Injuries  Fatality.Rate  \
Make
177mf llc                          0.0             2.0       0.000000
Migas                              0.0             1.0       0.000000
Mignet                             0.0             1.0       0.000000
Mike reed                          0.0             1.0       0.000000
Mikoyan gurevich                   0.0             2.0       0.000000
...                                ...             ...            ...
Boeing                           276.0          1228.0      14.795623
Airbus                           333.0           462.0       4.990385
Beech                            725.0          1260.0     305.323810
Piper                           1367.0          2824.0     617.666667
Cessna                          1900.0          4357.0     876.274603

                  Incident.Count    Rank
Make
177mf llc                      1  1032.0
Migas                          1  1032.0
Mignet                         1  1032.0
Mike reed                      1  1032.0
Mikoyan gurevich               2  1032.0
...                          ...     ...
Boeing                       377  2864.0
Airbus                        77  2865.0
Beech                       1267  2866.0
Piper                       3619  2867.0
Cessna                      6261  2868.0

[2868 rows x 5 columns]

In [ ]:
#df.to_csv('df_airplane_JE.csv')