# Data understanding

In [2]:
import pandas as pd 
import numpy as np
df = pd.read_csv('Data/Aviation_Data.csv')
df

/Users/DonJuve/anaconda3/envs/learn-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (6,7,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90343,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
90344,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90345,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
90346,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90347,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90348 entries, 0 to 90347
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      90348 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50249 non-null  object
 9   Airport.Name            52790 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87572 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81812 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82508 non-null  object
 30  Publication.Date        73659 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.4+ MB

In [4]:
df['Total.Fatal.Injuries']

0        2.0
1        4.0
2        3.0
3        2.0
4        1.0
        ...
90343    0.0
90344    0.0
90345    0.0
90346    0.0
90347    0.0
Name: Total.Fatal.Injuries, Length: 90348, dtype: float64

In [5]:
df['Total.Fatal.Injuries'].isna().sum()

12860

In [6]:
df['Total.Fatal.Injuries'].isna().sum()

12860

In [7]:
df['Total.Fatal.Injuries'].isna().sum()

12860

In [8]:
df['Total.Serious.Injuries'].isna().sum()

13969

In [9]:
df['Total.Minor.Injuries'].isna().sum()

13392

In [10]:
df['Total.Uninjured'].isna().sum()

7371

In [11]:
df['Report.Status'].isna().sum()

7840

In [12]:
df['Event.Date'].isna().sum()

1459

# Data Preparation

We will start by removing all the null value of the following colums of our Data Frames: 'Engine.Type','Model','Event.Date','Make','Injury.Severity','Total.Fatal.Injuries','Total.Serious.Injuries','Total.Minor.Injuries','Total.Uninjured'

In [13]:
df = df.dropna(subset=['Engine.Type','Model','Event.Date','Make','Injury.Severity','Total.Fatal.Injuries','Total.Serious.Injuries','Total.Minor.Injuries','Total.Uninjured' ])

In [14]:
df.shape

(68490, 31)

In [15]:
#verfication
df['Total.Serious.Injuries'].isna().sum()

0

In [16]:
df['Total.Uninjured'].isna().sum()

0

Verification of duplicate Values

In [17]:
df.duplicated().value_counts()
#to remove duplicates data

False    68490
dtype: int64

In [18]:
#remove all duplicates values
df = df.drop_duplicates()

In [19]:
#Sanity check
df.duplicated().value_counts()

False    68490
dtype: int64

In [20]:
df.shape

(68490, 31)

Normalization

In [21]:
df['Make']

0                  Stinson
1                    Piper
3                 Rockwell
6                   Cessna
7                   Cessna
               ...
90098               CESSNA
90106               CESSNA
90120                BEECH
90194    STEPHEN J HOFFMAN
90226             LUSCOMBE
Name: Make, Length: 68490, dtype: object

In [22]:
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
6,20001218X45446,Accident,CHI81LA106,1981-08-01,"COTTON, MN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,IMC,Unknown,Probable Cause,06-11-2001
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90098,20221011106092,Accident,CEN23LA008,2022-10-06,"Iola, TX",United States,304354N,0096752W,PVT,Private,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots failure to maintain control of the...,20-12-2022
90106,20221011106098,Accident,ERA23LA014,2022-10-08,"Dacula, GA",United States,034055N,0835224W,LZU,GWINNETT COUNTY - BRISCOE FLD,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,An in-flight collision with a bird while on ap...,20-12-2022
90120,20221018106153,Accident,CEN23LA015,2022-10-13,"Ardmore, OK",United States,034849N,0097722W,1F0,Ardmore Downtown Executive Air,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilot did not ensure adequate clearance fr...,20-12-2022
90194,20221031106231,Accident,CEN23LA023,2022-10-29,"Houston, TX",United States,293620N,0095959W,EFD,ELLINGTON,...,ASHO,NaN,0.0,1.0,0.0,0.0,VMC,NaN,The pilots failure to secure the magneto swit...,20-12-2022
90226,20221109106272,Accident,CEN23LA033,2022-11-09,"Bridgeport, TX",United States,331026N,0974943W,KXBP,Bridgeport Municipal,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The pilots loss of control due to a wind gust...,20-12-2022

In [23]:
df['Make']

0                  Stinson
1                    Piper
3                 Rockwell
6                   Cessna
7                   Cessna
               ...
90098               CESSNA
90106               CESSNA
90120                BEECH
90194    STEPHEN J HOFFMAN
90226             LUSCOMBE
Name: Make, Length: 68490, dtype: object

In [24]:
df['Make'] = df['Make'].str.capitalize()

In [25]:
df['Aircraft.Category'].unique()

array([nan, 'Airplane', 'Helicopter', 'Glider', 'Balloon', 'Gyrocraft',
       'Ultralight', 'Unknown', 'Weight-Shift', 'Powered Parachute',
       'Rocket', 'Blimp', 'WSFT'], dtype=object)

In [26]:
#df = df[df['Aircraft.Category'].str.lower().str.contains('airplane', na=False)]zz

In [43]:
df_airplane = df[df['Aircraft.Category'].str.contains('Airplane', na=False)]
df_airplane

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
14,20020917X02119,Accident,FTW82FPJ10,1982-01-02,"CHICKASHA, OK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90098,20221011106092,Accident,CEN23LA008,2022-10-06,"Iola, TX",United States,304354N,0096752W,PVT,Private,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots failure to maintain control of the...,20-12-2022
90106,20221011106098,Accident,ERA23LA014,2022-10-08,"Dacula, GA",United States,034055N,0835224W,LZU,GWINNETT COUNTY - BRISCOE FLD,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,An in-flight collision with a bird while on ap...,20-12-2022
90120,20221018106153,Accident,CEN23LA015,2022-10-13,"Ardmore, OK",United States,034849N,0097722W,1F0,Ardmore Downtown Executive Air,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilot did not ensure adequate clearance fr...,20-12-2022
90194,20221031106231,Accident,CEN23LA023,2022-10-29,"Houston, TX",United States,293620N,0095959W,EFD,ELLINGTON,...,ASHO,NaN,0.0,1.0,0.0,0.0,VMC,NaN,The pilots failure to secure the magneto swit...,20-12-2022
90226,20221109106272,Accident,CEN23LA033,2022-11-09,"Bridgeport, TX",United States,331026N,0974943W,KXBP,Bridgeport Municipal,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The pilots loss of control due to a wind gust...,20-12-2022

In [27]:
df = df[df['Aircraft.Category'] == 'Airplane']
df['Aircraft.Category']

7        Airplane
8        Airplane
12       Airplane
13       Airplane
14       Airplane
           ...
90098    Airplane
90106    Airplane
90120    Airplane
90194    Airplane
90226    Airplane
Name: Aircraft.Category, Length: 19883, dtype: object

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19883 entries, 7 to 90226
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                19883 non-null  object
 1   Investigation.Type      19883 non-null  object
 2   Accident.Number         19883 non-null  object
 3   Event.Date              19883 non-null  object
 4   Location                19883 non-null  object
 5   Country                 19877 non-null  object
 6   Latitude                16449 non-null  object
 7   Longitude               16449 non-null  object
 8   Airport.Code            13762 non-null  object
 9   Airport.Name            14398 non-null  object
 10  Injury.Severity         19883 non-null  object
 11  Aircraft.damage         19456 non-null  object
 12  Aircraft.Category       19883 non-null  object
 13  Registration.Number     19881 non-null  object
 14  Make                    19883 non-null  object
 15  Model                   19883 non-null  object
 16  Amateur.Built           19883 non-null  object
 17  Number.of.Engines       19388 non-null  float64
 18  Engine.Type             19883 non-null  object
 19  FAR.Description         19782 non-null  object
 20  Schedule                1626 non-null   object
 21  Purpose.of.flight       18615 non-null  object
 22  Air.carrier             9157 non-null   object
 23  Total.Fatal.Injuries    19883 non-null  float64
 24  Total.Serious.Injuries  19883 non-null  float64
 25  Total.Minor.Injuries    19883 non-null  float64
 26  Total.Uninjured         19883 non-null  float64
 27  Weather.Condition       19338 non-null  object
 28  Broad.phase.of.flight   3228 non-null   object
 29  Report.Status           18771 non-null  object
 30  Publication.Date        18650 non-null  object
dtypes: float64(5), object(26)
memory usage: 4.9+ MB

In [29]:
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
14,20020917X02119,Accident,FTW82FPJ10,1982-01-02,"CHICKASHA, OK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90098,20221011106092,Accident,CEN23LA008,2022-10-06,"Iola, TX",United States,304354N,0096752W,PVT,Private,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots failure to maintain control of the...,20-12-2022
90106,20221011106098,Accident,ERA23LA014,2022-10-08,"Dacula, GA",United States,034055N,0835224W,LZU,GWINNETT COUNTY - BRISCOE FLD,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,An in-flight collision with a bird while on ap...,20-12-2022
90120,20221018106153,Accident,CEN23LA015,2022-10-13,"Ardmore, OK",United States,034849N,0097722W,1F0,Ardmore Downtown Executive Air,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilot did not ensure adequate clearance fr...,20-12-2022
90194,20221031106231,Accident,CEN23LA023,2022-10-29,"Houston, TX",United States,293620N,0095959W,EFD,ELLINGTON,...,ASHO,NaN,0.0,1.0,0.0,0.0,VMC,NaN,The pilots failure to secure the magneto swit...,20-12-2022
90226,20221109106272,Accident,CEN23LA033,2022-11-09,"Bridgeport, TX",United States,331026N,0974943W,KXBP,Bridgeport Municipal,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The pilots loss of control due to a wind gust...,20-12-2022

In [30]:
df['Make'].value_counts()

Cessna             6261
Piper              3619
Beech              1267
Boeing              377
Mooney              310
                   ...
Boehlke kevin p       1
Durfee fred           1
Fahey william j       1
Martin curtis         1
Edward w gray         1
Name: Make, Length: 2868, dtype: int64

In [31]:
df_20 = df[df['Make'].isin(df['Make'].value_counts().nlargest(20).index)]

In [32]:
df_20

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
15,20020917X02117,Accident,FTW82FPG08,1982-01-02,"LITTLE ROCK, AR",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90089,20221011106095,Accident,CEN23LA011,2022-10-05,"Navasota, TX",United States,302315N,0096516W,60R,Navasota,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots loss of control while landing resu...,NaN
90098,20221011106092,Accident,CEN23LA008,2022-10-06,"Iola, TX",United States,304354N,0096752W,PVT,Private,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots failure to maintain control of the...,20-12-2022
90106,20221011106098,Accident,ERA23LA014,2022-10-08,"Dacula, GA",United States,034055N,0835224W,LZU,GWINNETT COUNTY - BRISCOE FLD,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,An in-flight collision with a bird while on ap...,20-12-2022
90120,20221018106153,Accident,CEN23LA015,2022-10-13,"Ardmore, OK",United States,034849N,0097722W,1F0,Ardmore Downtown Executive Air,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilot did not ensure adequate clearance fr...,20-12-2022
90226,20221109106272,Accident,CEN23LA033,2022-11-09,"Bridgeport, TX",United States,331026N,0974943W,KXBP,Bridgeport Municipal,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The pilots loss of control due to a wind gust...,20-12-2022

In [33]:
#df = df[df['Aircraft.Category'] == 'Airplane']
df_personal = df_20[df_20['Purpose.of.flight'] == 'Personal']

In [34]:
df_personal

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
15,20020917X02117,Accident,FTW82FPG08,1982-01-02,"LITTLE ROCK, AR",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
17,20020917X01656,Accident,ANC82FAG14,1982-01-02,"SKWENTA, AK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,3.0,0.0,0.0,0.0,VMC,Unknown,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90089,20221011106095,Accident,CEN23LA011,2022-10-05,"Navasota, TX",United States,302315N,0096516W,60R,Navasota,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots loss of control while landing resu...,NaN
90098,20221011106092,Accident,CEN23LA008,2022-10-06,"Iola, TX",United States,304354N,0096752W,PVT,Private,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilots failure to maintain control of the...,20-12-2022
90106,20221011106098,Accident,ERA23LA014,2022-10-08,"Dacula, GA",United States,034055N,0835224W,LZU,GWINNETT COUNTY - BRISCOE FLD,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,An in-flight collision with a bird while on ap...,20-12-2022
90120,20221018106153,Accident,CEN23LA015,2022-10-13,"Ardmore, OK",United States,034849N,0097722W,1F0,Ardmore Downtown Executive Air,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilot did not ensure adequate clearance fr...,20-12-2022
90226,20221109106272,Accident,CEN23LA033,2022-11-09,"Bridgeport, TX",United States,331026N,0974943W,KXBP,Bridgeport Municipal,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The pilots loss of control due to a wind gust...,20-12-2022

In [35]:
df_business = df_20[df_20['Purpose.of.flight'] == 'Business']

In [36]:
#filtered_df = df[(df['Total.Fatal.Injuries'] == 0) & (df['Total.Serious.Injuries'] == 0) & (df['Total.Minor.Injuries'] == 0)]

In [37]:
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

Safety Metric Calculation :

In [38]:
# first lets determine the total of the overall Injuries
df_20['Total.Injuries'] = df_20[['Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries']].sum(axis=1)

<ipython-input-38-c31a3e951e21>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_20['Total.Injuries'] = df_20[['Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries']].sum(axis=1)

In [39]:
df_20['Fatality.Rate'] = df_20['Total.Fatal.Injuries'] / df['Total.Injuries']

KeyError: 'Total.Injuries'

In [ ]:
#  Calculate Safety Metrics
#df['Total.Injuries'] = df[safety_columns[:-1]].sum(axis=1)
df_20.head()

Group data by categorie using the colummn Make

In [ ]:
df_new = df.groupby('Make')

In [ ]:
#creating the year column
df_20['Year'] = df_20['Event.Date'].str[:4]
print(df_20['Year'])

In [ ]:
ranked_companies = df_new[['Total.Fatal.Injuries', 'Total.Injuries', 'Fatality.Rate']].sum()
ranked_companies['Incident.Count'] = df_new.size()
ranked_companies['Rank'] = ranked_companies['Total.Fatal.Injuries'].rank(ascending=True)

In [ ]:
print(ranked_companies.sort_values(by='Rank'))

In [ ]:
#df.to_csv('df_airplane_JE.csv')

In [ ]:
import matplotlib.pyplot as plt

#fig, axs = plt.subplots(1, 3, figsize=(10, 18)) 
plt.figure(figsize=(10, 6))
                        
plt.bar(df_20['Make'], df_20['Total.Injuries'], color='blue')
plt.xlabel('Airlines companies')
plt.ylabel('total Injuries')
plt.title('Total injuries vs Make')
plt.tick_params (axis="x", labelrotation=90)                       
plt.show()

In [ ]:
df_20['Make'].values

In [ ]:
df_20['Total.Injuries']

In [ ]:
#fig, axs = plt.subplots(1, 3, figsize=(10, 18)) 
plt.figure(figsize=(10, 6))
plt.bar(df_20['Year'], df_20['Total.Fatal.Injuries'],color='blue')

#plt.xlabel(df_20['Make'].values)
plt.ylabel('total Injuries')
plt.title('Total Fatal injuries vs Years')
plt.tick_params (axis="x", labelrotation=90)   

plt.show()

fatalities vs phase of flight

In [ ]:
df_20['Broad.phase.of.flight']

In [ ]:
#fig, axs = plt.subplots(1, 3, figsize=(10, 18)) 
plt.figure(figsize=(10, 6))
plt.bar(df_20['Broad.phase.of.flight'], df_20['Total.Fatal.Injuries'],color='blue')

#plt.xlabel(df_20['Make'].values)
plt.ylabel('total Injuries')
plt.title('Phase of flight vs Fatal Injuries')
plt.tick_params (axis="x", labelrotation=90)   

plt.show()

fatalities vs phase of flight (as a company we need to focus on this particular phase)
number injured per per accident per year (fatal/severe/minor/uninjured)
injured vs purpose of flight
severity of accidents by type

In [ ]:
df_20.keys()

In [ ]:
df_20['Fatality.Rate']
df['your_column'] = df['your_column'].fillna(0)

In [ ]:
#fatalities vs phase of flight 
import matplotlib.pyplot as plt
x = df_20['Fatality.Rate'].astype(int)
#fig, axs = plt.subplots(1, 3, figsize=(10, 18)) 
plt.figure(figsize=(10, 6))
                        
plt.scatter(x, df_20['Broad.phase.of.flight'], color='blue')
plt.xlabel('Airlines companies')
plt.ylabel('total Injuries')
plt.title('Total injuries by Airlines')
plt.tick_params (axis="x", labelrotation=90)                       
plt.show()

In [ ]:
import matplotlib.pyplot as plt 
import numpy as np 
import math 
  
# Using Numpy to create an array X 
X = df_20['Make'] 
  
# Assign variables to the y axis part of the curve 
y = df_20['Year']
z = df_20['Total.Fatal.Injuries']
  
# Plotting both the curves simultaneously 
plt.plot(X, y, color='r', label='Year') 
plt.plot(X, z, color='g', label='Total Fatal Injuries') 
plt.tick_params (axis="x", labelrotation=90)  
# Naming the x-axis, y-axis and the whole graph 
plt.xlabel("Angle") 
plt.ylabel("Magnitude") 
plt.title("Sine and Cosine functions") 
  
# Adding legend, which helps us recognize the curve according to it's color 
plt.legend() 
  
# To load the display window 
plt.show()

In [40]:
df['Amateur.Built'].value_counts()

No     17383
Yes     2500
Name: Amateur.Built, dtype: int64

In [42]:
df['Make'].value_counts()

Cessna             6261
Piper              3619
Beech              1267
Boeing              377
Mooney              310
                   ...
Boehlke kevin p       1
Durfee fred           1
Fahey william j       1
Martin curtis         1
Edward w gray         1
Name: Make, Length: 2868, dtype: int64

In [85]:
df_airplane = pd.read_csv('Data/Airplane_data.csv')

/Users/DonJuve/anaconda3/envs/learn-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (29) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [86]:
df_airplane

,Unnamed: 0,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Year
0,5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,42.445277000000004,-70.758333,NaN,...,Air Canada,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017,1979
1,7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982,1982
2,8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,...,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982,1982
3,12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,...,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983,1982
4,13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,...,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983,1982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27612,90328,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022,2022
27613,90332,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,...,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022
27614,90335,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022,2022
27615,90336,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,...,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022,2022
27616,90345,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,...,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022

In [87]:
list(df_airplane['Make'].unique()[125:150])

['Davis',
 'Bellance',
 'Rockwell international',
 'Downer aircraft industries',
 'Ryan aeronautics',
 'Grumman american',
 nan,
 'Clancy',
 'Britten-norman',
 'Waco',
 'Pietenpol',
 'Miller',
 'Aeronca champion',
 'Coot',
 'Breezy',
 'Junior ace',
 'Globe',
 'Republic',
 "Rockwell int't",
 'Mong',
 'American',
 'Thorp',
 'Omac',
 'Bucker jungmann',
 'Steen']

In [88]:
df_airplane['Make']=df_airplane['Make'].replace("Rockwell International", "Rockwell Intl")

In [89]:
list(df_airplane['Make'].unique()[125:150])

['Davis',
 'Bellance',
 'Rockwell international',
 'Downer aircraft industries',
 'Ryan aeronautics',
 'Grumman american',
 nan,
 'Clancy',
 'Britten-norman',
 'Waco',
 'Pietenpol',
 'Miller',
 'Aeronca champion',
 'Coot',
 'Breezy',
 'Junior ace',
 'Globe',
 'Republic',
 "Rockwell int't",
 'Mong',
 'American',
 'Thorp',
 'Omac',
 'Bucker jungmann',
 'Steen']

In [93]:
df_airplane['Make']=df_airplane['Make'].replace("Rockwell int't", "Rockwell Intl")
df_airplane['Make']=df_airplane['Make'].replace('Rockwell international', "Rockwell Intl")

In [94]:
list(df_airplane['Make'].unique()[125:150])

['Davis',
 'Bellance',
 'Rockwell Intl',
 'Downer aircraft industries',
 'Ryan aeronautics',
 'Grumman american',
 nan,
 'Clancy',
 'Britten-norman',
 'Waco',
 'Pietenpol',
 'Miller',
 'Aeronca champion',
 'Coot',
 'Breezy',
 'Junior ace',
 'Globe',
 'Republic',
 'Mong',
 'American',
 'Thorp',
 'Omac',
 'Bucker jungmann',
 'Steen',
 'Alon']

In [97]:
df_airplane['Make'].value_counts()[30:60]

Bombardier inc                    65
Raytheon aircraft company         62
Rockwell Intl                     62
Ayres                             59
Grumman acft eng cor-schweizer    58
Rockwell                          57
Douglas                           55
Rans                              54
Swearingen                        52
American champion aircraft        52
Bombardier                        50
Grumman american avn. corp.       49
Diamond                           49
Flight design gmbh                49
Learjet                           48
Waco                              44
Quicksilver                       43
Zenith                            43
Airbus industrie                  43
Ayres corporation                 41
Fairchild                         39
Grumman american                  38
Lake                              36
Mooney aircraft corp.             34
Lancair                           33
Costruzioni aeronautiche tecna    33
Mitsubishi                        32
Evektor-aerotechnik as            30
Gulfstream                        30
Pitts                             30
Name: Make, dtype: int64

In [104]:
df_airplane['Make'].value_counts()

Cessna                            8475
Piper                             4715
Beech                             1692
Boeing                            1324
Mooney                             419
                                  ...
Thomas c sikes                       1
Flaglor                              1
Goodman robert bruce                 1
Boeing company, long beach div       1
Hebert                               1
Name: Make, Length: 3533, dtype: int64

In [115]:
df_airplane['Make']=df_airplane['Make'].replace('Rockwell', "Rockwell Intl")
df_airplane['Make']=df_airplane['Make'].replace('Rockwell comdr', "Rockwell Intl")
df_airplane['Make']=df_airplane['Make'].replace('Rockwell commander', "Rockwell Intl")


df_airplane['Make']=df_airplane['Make'].replace("Douglas", "Mcdonnell Douglas")
df_airplane['Make']=df_airplane['Make'].replace("Mcdonnell douglas", "Mcdonnell Douglas")
df_airplane['Make']=df_airplane['Make'].replace('Mcdonnell-douglas', "Mcdonnell Douglas")

df_airplane['Make']=df_airplane['Make'].replace('Bombardier inc', "Bombardier")
df_airplane['Make']=df_airplane['Make'].replace("Bombardier, inc.", "Bombardier")

df_airplane['Make']=df_airplane['Make'].replace("Cessna aircraft co", 'Cessna')
df_airplane['Make']=df_airplane['Make'].replace("Cessna aircraft company", 'Cessna')
df_airplane['Make']=df_airplane['Make'].replace("Cessna aircraft", 'Cessna')

df_airplane['Make']=df_airplane['Make'].replace("Gulfstream aerospace", 'Gulfstream')
df_airplane['Make']=df_airplane['Make'].replace("Gulfstream-schweizer a/c corp", 'Gulfstream')
df_airplane['Make']=df_airplane['Make'].replace("Gulfstream american corp", 'Gulfstream')
df_airplane['Make']=df_airplane['Make'].replace("Gulfstream-schweizer", 'Gulfstream')
df_airplane['Make']=df_airplane['Make'].replace('Gulfstream american', "Gulfstream")

df_airplane['Make']=df_airplane['Make'].replace("Czech aircraft works spol sro", 'Czech aircraft')
df_airplane['Make']=df_airplane['Make'].replace("Czech sport aircraft as", 'Czech aircraft')
df_airplane['Make']=df_airplane['Make'].replace("zech aircraft works", 'Czech aircraft')

df_airplane['Make']=df_airplane['Make'].replace("Learjet inc", "Learjet")
df_airplane['Make']=df_airplane['Make'].replace("Gates learjet corp.", "Learjet")
df_airplane['Make']=df_airplane['Make'].replace('Gates learjet', "Learjet")


df_airplane['Make']=df_airplane['Make'].replace("The boeing company", "Boeing")
df_airplane['Make']=df_airplane['Make'].replace("Boeing stearman", "Boeing")
df_airplane['Make']=df_airplane['Make'].replace('Smith mini', "Smith")
df_airplane['Make']=df_airplane['Make'].replace('Smith aerostar', "Smith")
df_airplane['Make']=df_airplane['Make'].replace('Smith miniplane', "Smith")
df_airplane['Make']=df_airplane['Make'].replace('Ted smith', "Smith")

In [110]:
df_airplane['Make'].value_counts()[200:250]

Evektor aerotechnik              6
Embraer-empresa brasileira de    6
Smith miniplane                  6
Dassault-breguet                 6
Antonov                          6
Nanchang china                   6
Sonex                            6
Challenger                       5
Velocity                         5
Stoddard hamilton                5
Cirrus design                    5
Taylorcraft aviation corp        5
Culver                           5
Progressive aerodyne             5
Fantasy air sro                  5
Piper/cub crafters               5
Eclipse aviation corp            5
Rans, inc.                       5
Boeing stearman                  5
Stearman aircraft                5
Czech aircraft works             5
Liberty aerospace inc.           5
Interstate                       5
Callair                          5
Miller                           5
Zlin                             5
Raytheon corporate jets          5
Classic aircraft corp            5
Curtiss-wright                   5
Monocoupe                        5
Extra flugzeugproduktions-und    5
Progressive aerodyne inc         5
Howard aircraft corp.            5
Thrush                           5
Scottish aviation                5
Steen                            5
Siai marchetti                   5
Partenavia                       5
Jones                            5
Canadair ltd                     4
Consolidated vultee              4
Morrisey                         4
Short bros. & harland            4
Pzl mielec                       4
Commander                        4
Clark                            4
Aero sp z o o                    4
Waco classic aircraft corp       4
Iai                              4
Robertson                        4
Name: Make, dtype: int64

In [112]:
df_airplane

,Unnamed: 0,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Year
0,5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,42.445277000000004,-70.758333,NaN,...,Air Canada,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017,1979
1,7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982,1982
2,8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,...,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982,1982
3,12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,...,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983,1982
4,13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,...,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983,1982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27612,90328,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022,2022
27613,90332,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,...,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022
27614,90335,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022,2022
27615,90336,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,...,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022,2022
27616,90345,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,...,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022

In [116]:
list(df_airplane['Make'].unique()[50:100])

['Luscombe',
 'Mckinley eaa',
 'Snow',
 'Champion',
 'Stinson',
 'Curtiss-wright',
 'Aero commander',
 'Piper-aerostar',
 'Rockwell intl.',
 'Ryan',
 'Jurca',
 'Martin-pitts',
 'Goodyear',
 'Rand',
 'Rutan',
 'Avres corp.',
 'Grum amer',
 'Evans aircraft',
 'Ayres',
 'Stampe renard',
 'Fairchild',
 'Pitts special',
 'Tailwind',
 'Aerotek-pitts',
 'North american',
 'Hartman',
 'Spezio',
 'Dauntless',
 'Christian',
 'Funk aircraft co.',
 'Mong sport',
 'Rayan',
 'Starfire',
 'Osprey',
 'Hudson',
 'Learjet',
 'Taylor',
 'Lake',
 'Volmer aircraft',
 'Citabria',
 'Martin',
 'Nash cassutt racer',
 'Playmate',
 'Oldfield',
 'Bac',
 'Erco',
 'Callair',
 'Consolidated aeronautics inc.',
 'Arctic',
 'Thurston']

In [117]:
df_airplane.to_csv('Airplane_data.csv')

In [118]:
df_airplane

,Unnamed: 0,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Year
0,5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,42.445277000000004,-70.758333,NaN,...,Air Canada,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017,1979
1,7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982,1982
2,8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,...,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982,1982
3,12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,...,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983,1982
4,13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,...,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983,1982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27612,90328,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022,2022
27613,90332,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,...,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022
27614,90335,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022,2022
27615,90336,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,...,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022,2022
27616,90345,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,...,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022